### PR TITLE
Generating path patterns with clownface-shacl-path

### PR DESCRIPTION
**Pull request by tpluscode**
For all intents and purposes, unless I made some terrible mistake, this PR should fix https://github.com/hypermedia-app/shape-to-query/issues/8 and effectively close https://github.com/hypermedia-app/shape-to-query/pull/7

@jeswr, would you like to have a look at the [preview deployment](https://visitor--shape-to-query.netlify.app/) and let me know if the resulting queries look correct to you?

### CODE REVIEW

**Comment by tpluscode** [comment]
For all intents and purposes, unless I made some terrible mistake, this PR should fix #8 and effectively replace #7 

@jeswr, would you like to have a look at the [preview deployment](https://visitor--shape-to-query.netlify.app/) and let me know if the resulting queries look correct to you?

**Comment by jeswr** [comment]
Just trying a few things now here are a few problematic tests cases which I'll post as individual comments

**Comment by jeswr** [comment]
1: 

```
sh:path ( [ sh:zeroOrMorePath rdf:type ] foaf:name ) ; 
```

generates

```rq
CONSTRUCT {       
  ?resource4 rdf:type ?resource3 .
  ?resource3 foaf:name ?resource2 .  
} WHERE {
  ?resource1 rdf:type* ?resource4 . 
  ?resource4 rdf:type ?resource3 .
  ?resource3 foaf:name ?resource2 .
}
```

which means that the `foaf:name` of the `?resource1` is not included when it should be.

**Comment by jeswr** [comment]
2:

```
sh:path [ sh:zeroOrOnePath rdf:type ] ; 
```

generates

```rq
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

CONSTRUCT {       
  ?resource1 rdf:type ?resource2 .  
} WHERE {
  {
    BIND(?resource1 as ?resource2)
  } UNION {
    ?resource1 rdf:type ?resource2 .
  }
}
```

which evaluated (using comunica) against

```ttl
@prefix : <http://example.org/> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .

:Jesse a :Person ;
  foaf:name "Jesse" .

:Person a :Thing ;
  foaf:name "Person" .
```

Gives
```
<http://example.org/Jesse> a <http://example.org/Person>.
<http://example.org/Person> a <http://example.org/Thing>.
```

Even though I would expect only 
```
<http://example.org/Jesse> a <http://example.org/Person>.
```

**Comment by jeswr** [comment]
3: 

Sequences with one path element are not supported

```
sh:path ( rdf:type ) ; 
```

**Comment by jeswr** [comment]
4:

Alternative paths with one alternative are not supported

```
sh:path [ sh:alternativePath ( rdf:type ) ] ;
```

**Comment by jeswr** [comment]
There is also a level of optimization work that can be done for instance 

```
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .

[
  a sh:NodeShape ;
  sh:property [
    sh:path foaf:name ;  
  ] ;
  sh:property [
    sh:path foaf:name ;  
  ] ;
] .
```

really just needs to generate `CONSRUCT WHERE { ?s foaf:name ?o }` rather than

```
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

CONSTRUCT { 
    
        
        ?resource1 foaf:name ?resource2 .
?resource1 foaf:name ?resource3 .
      
   }

WHERE {

    
        
        
        { ?resource1 foaf:name ?resource2 . }
      UNION
      { ?resource1 foaf:name ?resource3 . }
      
  
}

```

**Comment by tpluscode** [comment]
Thank you for a through review. You're right, I will push e2e tests running queries against a real store.

Regarding the problematic cases:

ad 1
For the `sh:zeroOrMorePath` I propose same pattern which I used for `sh:zeroOrOne` using `BIND`

ad 2

Why do you not expect `<http://example.org/Person>` ini the result? It does have "zero or one `rdf:type`"

ad 3 and 4

Yes, as defined by SHACL specification, both sequence and alternative paths require at least two elements in their lists.

**Comment by tpluscode** [comment]
> There is also a level of optimization work that can be done for instance

Definitely, optimisations will be possible. In this particular case I'd argue one should refactor the shape itself. Anyway, that is a topic for another day :)

**Comment by jeswr** [comment]
> Why do you not expect <http://example.org/Person> ini the result? It does have "zero or one rdf:type"

I think you might have misinterpreted what I said there - I do expect `<http://example.org/Jesse> a <http://example.org/Person>.`  (which is the one `rdf:type`) just not `<http://example.org/Person> a <http://example.org/Thing>.` (which is a path of 2 `rdf:type`s).

**Comment by tpluscode** [comment]
> I think you might have misinterpreted

The path translates to `?r rdf:type? ?t`. 

The triple `</Person> a </Thing>` does match that pattern, thus it is also returned with its type. Not because it's two `rdf:type` edges away from `</Jesse>

**Comment by jeswr** [comment]
> The triple </Person> a </Thing> does match that pattern,

Oh right - my bad. My use case involves a lot of `targetNode`s (hence the issue I opened) so I had that with the mindset of targeting the node Jesse.

**Pull request merged**
